from datetime import datetime, timedelta, timezone

import jwt

from app import auth


def test_hash_and_verify_roundtrip():
    hashed = auth.hash_password("correct horse battery staple")
    assert hashed != "correct horse battery staple"
    assert auth.verify_password("correct horse battery staple", hashed) is True
    assert auth.verify_password("wrong password", hashed) is False


def test_create_and_decode_token_roundtrip():
    token = auth.create_token("user-123", "alice")
    payload = auth.decode_token(token)
    assert payload is not None
    assert payload["user_id"] == "user-123"
    assert payload["username"] == "alice"


def test_expired_token_is_rejected():
    expired = datetime.now(timezone.utc) - timedelta(seconds=1)
    payload = {"user_id": "u", "username": "bob", "exp": expired}
    token = jwt.encode(payload, auth._SECRET_KEY, algorithm=auth.ALGORITHM)
    assert auth.decode_token(token) is None


def test_create_token_includes_token_version():
    token = auth.create_token("user-123", "alice", token_version=3)
    payload = auth.decode_token(token)
    assert payload is not None
    assert payload["tv"] == 3
    assert payload["user_id"] == "user-123"


def test_bcrypt_hash_format_and_roundtrip():
    """Direct-bcrypt hashing (passlib dropped) must keep the $2b$ cost-12 format."""
    h = auth.hash_password("student-password-123")
    assert h.startswith("$2b$12$"), h[:10]
    assert auth.verify_password("student-password-123", h) is True
    assert auth.verify_password("student-password-124", h) is False


def test_verify_accepts_passlib_era_hashes():
    """Passwords stored before the passlib->bcrypt switch must still log in.

    This hash was generated by passlib's CryptContext(schemes=["bcrypt"]) for
    the password below. If this test fails, the migration locked every existing
    user out of their account.
    """
    legacy = "$2b$12$/5Z9wYfZFzEv8pwfEme29OqIqXRS65e/4QkDyXfBzSrm81rT1QSqi"
    assert auth.verify_password("legacy-passlib-password", legacy) is True
    assert auth.verify_password("some-other-password", legacy) is False


def test_verify_returns_false_on_malformed_hash():
    """A corrupt/truncated stored hash must not raise a 500 during login."""
    for bad in ("", "not-a-hash", "$2b$12$tooshort", "$2b$12$" + "x" * 10, None):
        assert auth.verify_password("whatever", bad) is False


def test_hash_rejects_oversized_password():
    """bcrypt silently ignores bytes past 72; refuse instead of truncating."""
    import pytest as _pytest
    with _pytest.raises(ValueError):
        auth.hash_password("a" * 73)
